[package]
name = "names"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = "0.8.2"
rand = "0.8.4"
convert_case = "0.4.0"


[dev-dependencies]
regex = "1.5.4"
