[package]
name = "kind"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kind_derive = { path = "../kind-derive"}
k8s-openapi = { version = "0.13.0", features = ["v1_21"] }