[package]
name = "error"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-derive = { path = "../error-derive" }
httpcode = { path = "../httpcode" }
kind = { path = "../kind" }
serde_json = "1.0.64"
serde = "1.0.126"
rocket = "0.5.0-rc.1"
thiserror = "1.0.26"

[dev-dependencies]
rocket = { version = "0.5.0-rc.1", features = ["json"]}