[package]
name = "httpcode-derive"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.28"
syn = {version = "1.0.74", features = ["derive"] }
quote = "1.0.9"