[package]
name = "os"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.8.1", default_features = false, features = ["process"] }

error = { path = "../error" }
result = { path = "../result" }

[dev-dependencies]
tokio-test = "0.4.2"