[package]
name = "k8s"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kube = { version = "0.59.0", default-features = false, features = ["client", "rustls-tls"] }
kube-runtime = "0.59.0"
k8s-openapi = { version = "0.13.0", features = ["v1_21"] }
serde_json = "1.0.64"
serde = "1.0.126"
tokio = "1.8.1"
tokio-util = "0.6.7"
either = "1.6.1"

derivative = "2.2.0"
snafu = "0.6.10"
smallvec = "1.6.1"
futures = "0.3.16"
futures-util = "0.3.16"

bytes = "1.0.1"
async-trait = "0.1.51"


error = { path = "../error" }
result = { path = "../result" }
httpcode = { path = "../httpcode" }
kind = { path = "../kind" }
names = { path = "../names" }

[dev-dependencies]
tokio-test = "0.4.2"