{{ if eq .Values.registry.implementation "ECR" }}
apiVersion: v1
kind: Secret
metadata:
  name: ocf-aws
  namespace: ocf-system
type: Opaque
stringData:
  # Region is not very...secret...but it makes it
  # easier to have all AWS related stuff bundled together.
  AWS_REGION: {{ .Values.aws.region }}
  AWS_ACCESS_KEY_ID: {{ .Values.aws.aws_access_key_id }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.aws_secret_access_key }}
  AWS_USERNAME: {{ .Values.aws.aws_username }}
{{ end }}
