name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Compile
    steps:
      - uses: actions/checkout@v2
      - name: Load Cache
        uses: Swatinem/rust-cache@v1
        with:
          working-directory: ./k8s
      - uses: actions-rs/cargo@v1
        name: Compile
        with:
          command: build
          args: --release --workspace --manifest-path ./k8s/Cargo.toml
      - name: Archive the ACM
        uses: actions/upload-artifact@v2
        with:
          name: acm
          path: k8s/target/release/acm
      - name: Archive the AIM
        uses: actions/upload-artifact@v2
        with:
          name: aim
          path: k8s/target/release/aim

  docker:
    needs: compile
    runs-on: ubuntu-latest
    name: Build Images
    steps:
      - uses: actions/checkout@v2
      - name: Prep Workspace
        run: mkdir -p k8s/target/release
      - name: Download the Archived ACM
        uses: actions/download-artifact@v2
        with:
          name: acm
          path: k8s/target/release
      - name: Download the Archived AIM
        uses: actions/download-artifact@v2
        with:
          name: aim
          path: k8s/target/release
      - name: Package
        working-directory: k8s
        run: ./package.sh
        env:
          REGISTRY: 248135293344.dkr.ecr.us-east-2.amazonaws.com
      - name: Archive the ACM
        uses: actions/upload-artifact@v2
        with:
          name: acm
          path: k8s/target/images/acm/acm
      - name: Archive the AIM
        uses: actions/upload-artifact@v2
        with:
          name: aim
          path: k8s/target/images/aim/aim
      - name: Archive containerd
        uses: actions/upload-artifact@v2
        with:
          name: containerd
          path: k8s/target/images/containerd/containerd

  helm:
    runs-on: ubuntu-latest
    name: Package Helm Charts
    steps:
      - uses: actions/checkout@v2
      - name: Package Helm Charts
        working-directory: ./k8s
        run: |
          source version.env
          helm package --version "${VERSION}" --app-version "${VERSION}" ./helm
          mv acm-"${VERSION}.tgz acm.tgz
      - name: Archive Helm Charts
        uses: actions/upload-artifact@v2
        with:
          name: acm_helm_charts
          path: k8s/acm.tgz

  release:
    needs: [docker, helm]
    name: Release to ECR
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2

      - name: Download the Archived ACM
        uses: actions/download-artifact@v2
        with:
          name: acm
      - name: Download the Archived AIM
        uses: actions/download-artifact@v2
        with:
          name: aim
      - name: Download the Archived containerd
        uses: actions/download-artifact@v2
        with:
          name: aim
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION  }}
      - name: Log Into ECR
        run: aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin "${REGISTRY}"
        env:
          REGISTRY: 248135293344.dkr.ecr.us-east-2.amazonaws.com