name: Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    name: Fake Build
    steps:
      - uses: actions/checkout@v2
      - name: Make file
        run: date > wat
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: datetime
          path: ./wat
      - name: Docker pull
        run: docker pull alpine

  checking:
    runs-on: ubuntu-latest
    name: Fake Build
    steps:
      - name: docker ls
        run: docker images

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: datetime
      - name: Checkit
        run: ls
      - name: Checkit 2
        run: cat wat