name: Release

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    name: Push to ECR
    steps:
    - uses: actions/checkout@v2
    - name: Load Cache
      uses: Swatinem/rust-cache@v1
    - name: Build
      run: cargo build --release
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION  }}
#    - name: Push Smoke
#      run: ./sweep_the_leg.sh
    
