name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Load cache
      uses: Swatinem/rust-cache@v1
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --release
    - name: Docker smoke
      run: docker images
    - name: Target smoke
      run: ls target
    - name: Push Smoke
      run: ./sweep_the_leg.sh
    
