name: Unit Tests

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Load Cache
        uses: Swatinem/rust-cache@v1
      - name: Run Tests
        run: cargo test --release
