name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  unit_tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Load cache
        uses: Swatinem/rust-cache@v1
      - name: Run tests
        run: cargo test --release
