name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Load Cache
        uses: Swatinem/rust-cache@v1
      - name: Run Unit Tests
        run: cargo test --release
